### ISSUE TITLE
拖拽到项目中，bundle引用问题

### ISSUE THREAD

**Issue by admintestgithub** [DoTalkLily/LYWebViewController#1]
手动复制到项目中，所有的LYWebViewControllerLocalizedString都引用不到。请问需要怎么设置?

**Comment by DoTalkLily** [comment]
你好，先看下你的项目里是否配置了国际化：project->Info->Localizations
![image](https://user-images.githubusercontent.com/3271333/31368118-4d7d8618-ad41-11e7-80c6-97d3e7ae7e80.png)

设置之后如果报xxx.strings 文件找不到可以试下这个方法：
1. Try to run the app, it will show the mentioned error
2. Now, right-click on storybook file and click on “Show in Finder”
3. From the directory location, move out the .storyboard file from Base.lproj folder
4. Now go back to Xcode, and remove the storyboard file (only reference)
5. Now, drag the .storyboard file from its new location into the project
